Output function for simulation results, issue #26
Thousandaire/thousandaire pull request #27
Opened 2020-11-17 03:30 UTC by ioumu8

Before front end is built, we need a clear way to read the simulation results.
This function change the simulation results into pandas DataFrame to make it easier to read the results.

2020-11-22 20:44 UTC, b821213 requested changes
1. `results_skin.py` won't be used by anyone except `simulation.py`, and at least for the time being we don't expect a second function needed in the future. I think we don't need to add an independent file just for a function that only one client uses.
2. This PR now  has conflicts with origin/master. Please resolve those confliction.

2020-11-23 04:23 UTC, ioumu8 reviewed
Output format for eval_results is not built.

2020-11-27 15:47 UTC, b821213 commented on simulation.py
> +        print(alpha_path, out_put_on_cmd(results, instruments),
I found that this will print out only heads and tails of the data frame. Is it possible to print out all of them?

2020-11-27 15:49 UTC, b821213 commented on simulation.py
> +def out_put_on_cmd(results, instruments):
Can this be convert_to_dataframe?  It only converts `results` to format `pandas.DataFrame` rather than outputs anything.

2020-11-27 15:54 UTC, b821213 commented on simulation.py
> +            path, results, eval_results, instruments = results_queue.get()
I prefer put `instrument` in the second position because it is more "basic".

2021-01-02 00:11 UTC, b821213 approved these changes
LGTM

2021-01-03 06:35 UTC, merged